In [1]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

##### 1)	Create an array containing 4 string elements: your first name, your last name, your birth state and your favorite color. 

In [2]:
me = make_array("Jefferson", "Sesler", "Virginia", "Green")
me

array(['Jefferson', 'Sesler', 'Virginia', 'Green'], dtype='<U9')

###### a.	Use a numpy function to make all elements uppercase. 

In [3]:
me = np.char.upper(me)
me

array(['JEFFERSON', 'SESLER', 'VIRGINIA', 'GREEN'], dtype='<U9')

###### b.	Use a numpy function to count the number of times the letter “a” appears in each element of your array.

In [4]:
count_a = np.char.count(me, "a")
count_a

array([0, 0, 0, 0])

###### c.	Optional: Use a numpy function to find the length of each element in the array. You may need to Google this. 

In [5]:
lengths = [len(i) for i in me]
lengths

[9, 6, 8, 5]

##### 2)	Create an array containing EVERY OTHER odd number starting with 1 and ending with (and including) 41. 

In [6]:
odds = np.arange(1, 42, 4)
odds

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

###### a.	Use numpy to find the sum and the product of the elements of this array. NOTE: This will require you to convert the elements of your array to floats using the astype method.

In [7]:
addition = np.sum(odds)
multiplication = np.prod(odds.astype(float))
print(addition)
print(multiplication)

231
7579867420125.0


###### b.	Use numpy to take the natural log of each element.

In [8]:
natural = np.log(odds)
natural

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])

###### c.	Optional: The numpy function np.diff finds the difference between adjacent elements of an array. Find the SUM of adjacent elements of this array. 

In [9]:
oddsLen = len(odds)
adjSums = odds[0:oddsLen-1] + odds[1:oddsLen]
adjSums

array([ 6, 14, 22, 30, 38, 46, 54, 62, 70, 78])